# Generated by Django 2.2.10 on 2020-07-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200722_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('pinterest', 'fa-pinterest'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
