# Generated by Django 2.2.10 on 2020-07-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200723_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest'), ('instagram', 'fa-instagram'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
