# Generated by Django 2.2.10 on 2020-07-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='price',
            new_name='prix',
        ),
    ]
